# Generated by Django 5.2.14 on 2026-06-03 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecoponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(default='', max_length=200)),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='parceiros/')),
                ('site_url', models.URLField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SlideCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='carrossel/')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TempoDecomposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('tempo', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='reportes/')),
                ('endereco', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('DENUNCIA', 'Foco de Problema'), ('COLETA', 'Descarte/Reciclagem')], default='DENUNCIA', max_length=10)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('analise_ia', models.TextField(blank=True, null=True)),
                ('urgencia', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=10)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('projeto_nome', models.CharField(default='Drive-Thru Sustentabilidade', max_length=100)),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='painel.parceiro')),
            ],
        ),
    ]
