# Generated by Django 5.2.14 on 2026-06-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidecarrossel',
            name='dado_numerico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slidecarrossel',
            name='icone_dado',
            field=models.CharField(blank=True, help_text='Classe do ícone (ex: fa-solid fa-clock)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slidecarrossel',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
