# Generated by Django 5.2.14 on 2026-06-04 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_slidecarrossel_dado_numerico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='empresa_dona',
            field=models.ForeignKey(blank=True, help_text='Se for uma ação interna ou evento privado, vincule a empresa aqui.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slidecarrossel',
            name='icone_dado',
            field=models.CharField(blank=True, help_text='Classe do ícone', max_length=50, null=True),
        ),
    ]
