# Generated by Django 5.2.14 on 2026-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_reporte_empresa_dona_alter_slidecarrossel_icone_dado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidecarrossel',
            name='icone_dado',
        ),
        migrations.RemoveField(
            model_name='slidecarrossel',
            name='imagem',
        ),
        migrations.AddField(
            model_name='slidecarrossel',
            name='icone',
            field=models.ImageField(blank=True, help_text='Faça upload do seu ícone em PNG translúcido ou GIF animado aqui.', null=True, upload_to='carrossel_icones/'),
        ),
    ]
