# Generated by Django 5.2.11 on 2026-06-19 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_categoriamaterial_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecoponto',
        ),
        migrations.AlterField(
            model_name='categoriamaterial',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Categoria (ex: Papel, Vidro)'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='empresa_dona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='projeto_nome',
            field=models.CharField(blank=True, default='Visão Cidadã', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('IRREGULARIDADE', 'Reporte de Irregularidade')], default='IRREGULARIDADE', max_length=20),
        ),
        migrations.AlterField(
            model_name='slidecarrossel',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='carrossel_icones/'),
        ),
    ]
