# Generated by Django 5.2.14 on 2026-06-24 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_delete_ecoponto_alter_categoriamaterial_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetaESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acao', models.CharField(default='Drive-Thru da Sustentabilidade', max_length=200)),
                ('data_acao', models.DateField(auto_now_add=True, verbose_name='Data da Ação')),
                ('kg_plastico', models.FloatField(default=0, verbose_name='Plástico (kg)')),
                ('kg_vidro', models.FloatField(default=0, verbose_name='Vidro (kg)')),
                ('kg_papel', models.FloatField(default=0, verbose_name='Papel/Papelão (kg)')),
                ('litros_agua_poupada', models.FloatField(default=0, verbose_name='Água Poupada (L)')),
                ('kg_co2_evitado', models.FloatField(default=0, verbose_name='CO2 Evitado (kg)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empresa Parceira')),
            ],
        ),
    ]
