# Generated by Django 5.2.14 on 2026-06-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_coletaesg'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletaesg',
            name='analise_ia',
            field=models.TextField(blank=True, verbose_name='Laudo Gerado (IA)'),
        ),
        migrations.AddField(
            model_name='coletaesg',
            name='kg_metal',
            field=models.FloatField(default=0, verbose_name='Metal/Alumínio (kg)'),
        ),
        migrations.AddField(
            model_name='coletaesg',
            name='kg_organico',
            field=models.FloatField(default=0, verbose_name='Orgânico/Compostagem (kg)'),
        ),
        migrations.AlterField(
            model_name='coletaesg',
            name='nome_acao',
            field=models.CharField(default='Drive-Thru da Sustentabilidade', max_length=200, verbose_name='Nome do Evento/Ação'),
        ),
    ]
