# Generated by Django 5.2.14 on 2026-06-25 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_coletaesg_analise_ia_coletaesg_kg_metal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletaesg',
            name='data_coleta',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Ação'),
        ),
    ]
